import type { AnchorRole, HueWindow, MoodAnchor } from '@/features/palette-generator'
import type { RandomArchetype } from './types'

function anchor(
  h: number,
  c: number,
  l: number,
  role: AnchorRole,
  jitterH = 8,
  jitterC = 0.015,
  jitterL = 0.04,
): MoodAnchor {
  return { h, c, l, role, jitterH, jitterC, jitterL }
}

/** Rotates a whole archetype's hues by `degrees` — used for `rotatable` archetypes so a "relationship" (analogous, triadic, ...) can land anywhere on the wheel instead of always the same authored hue. */
export function rotateArchetype(archetype: RandomArchetype, degrees: number): RandomArchetype {
  const rotateHue = (h: number) => ((h + degrees) % 360 + 360) % 360
  const rotateWindow = (w: HueWindow) => ({ start: rotateHue(w.start), end: rotateHue(w.end) })
  return {
    ...archetype,
    anchors: archetype.anchors.map((a) => ({ ...a, h: rotateHue(a.h) })),
    hueWindows: archetype.hueWindows.map(rotateWindow),
    forbidden: archetype.forbidden.map((z) => ({ ...z, start: rotateHue(z.start), end: rotateHue(z.end) })),
  }
}

/**
 * 18 curated random-palette styles — see docs/random-palette.md for how
 * these feed `generateFromFamily`. The 6 `rotatable: true` archetypes
 * define a hue *relationship* at hue 0 and get rotated to a random
 * position each generation; the other 12 have a fixed color identity
 * (like a mood family) and are never rotated.
 */
export const RANDOM_ARCHETYPES: RandomArchetype[] = [
  {
    id: 'soft-analogous',
    label: 'Soft Analogous',
    rotatable: true,
    anchors: [
      anchor(0, 0.06, 0.72, 'main'),
      anchor(330, 0.05, 0.78, 'main'),
      anchor(30, 0.045, 0.66, 'support'),
      anchor(0, 0.02, 0.93, 'neutral-light'),
      anchor(0, 0.04, 0.32, 'neutral-dark'),
    ],
    hueWindows: [{ start: 300, end: 60 }],
    chromaRange: [0.02, 0.09],
    lightnessRange: [0.28, 0.95],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'mixed',
    contrast: 'low',
    intensityBaseline: 'soft',
    neutralProbability: 0.7,
  },
  {
    id: 'bold-analogous',
    label: 'Bold Analogous',
    rotatable: true,
    anchors: [
      anchor(0, 0.19, 0.6, 'main'),
      anchor(330, 0.17, 0.68, 'main'),
      anchor(30, 0.15, 0.55, 'support'),
      anchor(0, 0.03, 0.9, 'neutral-light'),
      anchor(0, 0.08, 0.28, 'neutral-dark'),
    ],
    hueWindows: [{ start: 300, end: 60 }],
    chromaRange: [0.12, 0.22],
    lightnessRange: [0.24, 0.92],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'mixed',
    contrast: 'high',
    intensityBaseline: 'vibrant',
    neutralProbability: 0.5,
  },
  {
    id: 'split-complementary',
    label: 'Split Complementary',
    rotatable: true,
    anchors: [
      anchor(0, 0.15, 0.58, 'main'),
      anchor(150, 0.13, 0.62, 'support'),
      anchor(210, 0.13, 0.6, 'accent'),
      anchor(0, 0.02, 0.92, 'neutral-light'),
      anchor(0, 0.05, 0.3, 'neutral-dark'),
    ],
    hueWindows: [
      { start: 340, end: 20 },
      { start: 130, end: 170 },
      { start: 190, end: 230 },
    ],
    chromaRange: [0.08, 0.18],
    lightnessRange: [0.26, 0.93],
    forbidden: [],
    defaultHarmony: 'split-complementary',
    warmth: 'mixed',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.6,
  },
  {
    id: 'triadic-balanced',
    label: 'Triadic Balanced',
    rotatable: true,
    anchors: [
      anchor(0, 0.14, 0.58, 'main'),
      anchor(120, 0.13, 0.55, 'support'),
      anchor(240, 0.13, 0.55, 'accent'),
      anchor(0, 0.02, 0.92, 'neutral-light'),
      anchor(0, 0.05, 0.3, 'neutral-dark'),
    ],
    hueWindows: [
      { start: 340, end: 20 },
      { start: 100, end: 140 },
      { start: 220, end: 260 },
    ],
    chromaRange: [0.08, 0.16],
    lightnessRange: [0.26, 0.92],
    forbidden: [],
    defaultHarmony: 'triadic',
    warmth: 'mixed',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.6,
  },
  {
    id: 'warm-core-cool-accent',
    label: 'Warm Core, Cool Accent',
    rotatable: false,
    anchors: [
      anchor(30, 0.13, 0.6, 'main'),
      anchor(45, 0.11, 0.72, 'main'),
      anchor(20, 0.09, 0.5, 'support'),
      anchor(210, 0.1, 0.58, 'accent', 8, 0.02, 0.05),
      anchor(85, 0.03, 0.9, 'neutral-light'),
      anchor(30, 0.05, 0.28, 'neutral-dark'),
    ],
    hueWindows: [
      { start: 340, end: 70 },
      { start: 190, end: 230 },
    ],
    chromaRange: [0.03, 0.15],
    lightnessRange: [0.24, 0.92],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'warm',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.6,
  },
  {
    id: 'cool-core-warm-accent',
    label: 'Cool Core, Warm Accent',
    rotatable: false,
    anchors: [
      anchor(210, 0.12, 0.6, 'main'),
      anchor(230, 0.1, 0.52, 'main'),
      anchor(195, 0.08, 0.72, 'support'),
      anchor(30, 0.11, 0.62, 'accent', 8, 0.02, 0.05),
      anchor(210, 0.025, 0.92, 'neutral-light'),
      anchor(230, 0.05, 0.28, 'neutral-dark'),
    ],
    hueWindows: [
      { start: 180, end: 250 },
      { start: 15, end: 50 },
    ],
    chromaRange: [0.03, 0.14],
    lightnessRange: [0.24, 0.93],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'cool',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.6,
  },
  {
    id: 'neutral-plus-two-accents',
    label: 'Neutral Plus Two Accents',
    rotatable: true,
    anchors: [
      anchor(0, 0.01, 0.92, 'neutral-light'),
      anchor(0, 0.015, 0.6, 'support'),
      anchor(0, 0.02, 0.25, 'neutral-dark'),
      anchor(0, 0.17, 0.58, 'main'),
      anchor(170, 0.15, 0.55, 'accent'),
    ],
    hueWindows: [
      { start: 340, end: 20 },
      { start: 150, end: 190 },
    ],
    chromaRange: [0.01, 0.19],
    lightnessRange: [0.2, 0.95],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'mixed',
    contrast: 'high',
    intensityBaseline: 'balanced',
    neutralProbability: 0.9,
  },
  {
    id: 'light-to-dark-tonal',
    label: 'Light to Dark Tonal',
    rotatable: true,
    anchors: [
      anchor(0, 0.1, 0.55, 'main'),
      anchor(0, 0.02, 0.92, 'neutral-light'),
      anchor(0, 0.06, 0.14, 'neutral-dark'),
    ],
    hueWindows: [{ start: 340, end: 20 }],
    chromaRange: [0.03, 0.14],
    lightnessRange: [0.1, 0.95],
    forbidden: [],
    defaultHarmony: 'monochrome',
    warmth: 'mixed',
    contrast: 'high',
    intensityBaseline: 'balanced',
    neutralProbability: 0.4,
  },
  {
    id: 'pastel-mixed',
    label: 'Pastel Mixed',
    rotatable: false,
    anchors: [
      anchor(350, 0.07, 0.87, 'main'),
      anchor(45, 0.065, 0.88, 'support'),
      anchor(150, 0.06, 0.88, 'main'),
      anchor(235, 0.06, 0.87, 'support'),
      anchor(300, 0.065, 0.86, 'accent'),
      anchor(90, 0.02, 0.94, 'neutral-light'),
    ],
    hueWindows: [{ start: 0, end: 360 }],
    chromaRange: [0.02, 0.09],
    lightnessRange: [0.78, 0.96],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'mixed',
    contrast: 'low',
    intensityBaseline: 'soft',
    neutralProbability: 0.5,
  },
  {
    id: 'candy',
    label: 'Candy',
    rotatable: false,
    anchors: [
      anchor(340, 0.18, 0.72, 'main'),
      anchor(280, 0.15, 0.68, 'main'),
      anchor(195, 0.14, 0.75, 'support'),
      anchor(50, 0.16, 0.8, 'accent'),
      anchor(340, 0.02, 0.92, 'neutral-light'),
    ],
    hueWindows: [{ start: 0, end: 360 }],
    chromaRange: [0.1, 0.22],
    lightnessRange: [0.55, 0.93],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'mixed',
    contrast: 'high',
    intensityBaseline: 'vibrant',
    neutralProbability: 0.4,
  },
  {
    id: 'vintage',
    label: 'Vintage',
    rotatable: false,
    anchors: [
      anchor(40, 0.09, 0.65, 'main'),
      anchor(20, 0.11, 0.5, 'main'),
      anchor(100, 0.07, 0.5, 'support'),
      anchor(250, 0.05, 0.55, 'accent'),
      anchor(60, 0.04, 0.88, 'neutral-light'),
      anchor(30, 0.05, 0.3, 'neutral-dark'),
    ],
    hueWindows: [{ start: 5, end: 270 }],
    chromaRange: [0.02, 0.11],
    lightnessRange: [0.25, 0.88],
    forbidden: [{ start: 280, end: 340, minChroma: 0.06 }],
    defaultHarmony: 'analogous',
    warmth: 'mixed',
    contrast: 'medium',
    intensityBaseline: 'soft',
    neutralProbability: 0.6,
  },
  {
    id: 'nature',
    label: 'Nature',
    rotatable: false,
    anchors: [
      anchor(110, 0.09, 0.5, 'main'),
      anchor(90, 0.07, 0.62, 'main'),
      anchor(40, 0.08, 0.45, 'support'),
      anchor(190, 0.07, 0.6, 'accent'),
      anchor(85, 0.04, 0.85, 'neutral-light'),
      anchor(100, 0.05, 0.3, 'neutral-dark'),
    ],
    hueWindows: [{ start: 15, end: 220 }],
    chromaRange: [0.02, 0.13],
    lightnessRange: [0.22, 0.88],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'mixed',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.6,
  },
  {
    id: 'editorial-bold',
    label: 'Editorial Bold',
    rotatable: false,
    anchors: [
      anchor(0, 0.005, 0.97, 'neutral-light'),
      anchor(0, 0.01, 0.08, 'neutral-dark'),
      anchor(0, 0.18, 0.5, 'main'),
      anchor(210, 0.16, 0.45, 'accent'),
    ],
    hueWindows: [
      { start: 340, end: 20 },
      { start: 190, end: 230 },
    ],
    chromaRange: [0.005, 0.2],
    lightnessRange: [0.06, 0.98],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'mixed',
    contrast: 'high',
    intensityBaseline: 'vibrant',
    neutralProbability: 0.7,
  },
  {
    id: 'sunset',
    label: 'Sunset',
    rotatable: false,
    anchors: [
      anchor(20, 0.15, 0.62, 'main'),
      anchor(340, 0.13, 0.55, 'main'),
      anchor(300, 0.1, 0.42, 'support'),
      anchor(45, 0.14, 0.75, 'accent'),
      anchor(270, 0.08, 0.28, 'neutral-dark'),
    ],
    hueWindows: [{ start: 260, end: 70 }],
    chromaRange: [0.05, 0.19],
    lightnessRange: [0.24, 0.85],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'warm',
    contrast: 'high',
    intensityBaseline: 'vibrant',
    neutralProbability: 0.3,
  },
  {
    id: 'ocean',
    label: 'Ocean',
    rotatable: false,
    anchors: [
      anchor(210, 0.11, 0.5, 'main'),
      anchor(190, 0.1, 0.62, 'main'),
      anchor(175, 0.08, 0.72, 'support'),
      anchor(230, 0.09, 0.4, 'accent'),
      anchor(200, 0.02, 0.93, 'neutral-light'),
    ],
    hueWindows: [{ start: 160, end: 250 }],
    chromaRange: [0.03, 0.15],
    lightnessRange: [0.22, 0.95],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'cool',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.5,
  },
  {
    id: 'garden',
    label: 'Garden',
    rotatable: false,
    anchors: [
      anchor(120, 0.09, 0.5, 'main'),
      anchor(340, 0.13, 0.7, 'main'),
      anchor(60, 0.12, 0.78, 'support'),
      anchor(280, 0.1, 0.6, 'accent'),
      anchor(90, 0.03, 0.9, 'neutral-light'),
    ],
    hueWindows: [{ start: 0, end: 360 }],
    chromaRange: [0.03, 0.15],
    lightnessRange: [0.38, 0.92],
    forbidden: [],
    defaultHarmony: 'balanced',
    warmth: 'mixed',
    contrast: 'medium',
    intensityBaseline: 'balanced',
    neutralProbability: 0.5,
  },
  {
    id: 'dessert',
    label: 'Dessert',
    rotatable: false,
    anchors: [
      anchor(30, 0.09, 0.68, 'main'),
      anchor(350, 0.1, 0.75, 'main'),
      anchor(60, 0.06, 0.85, 'support'),
      anchor(20, 0.07, 0.5, 'accent'),
      anchor(40, 0.02, 0.93, 'neutral-light'),
    ],
    hueWindows: [{ start: 300, end: 80 }],
    chromaRange: [0.02, 0.13],
    lightnessRange: [0.3, 0.94],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'warm',
    contrast: 'medium',
    intensityBaseline: 'soft',
    neutralProbability: 0.5,
  },
  {
    id: 'night-sky',
    label: 'Night Sky',
    rotatable: false,
    anchors: [
      anchor(250, 0.06, 0.15, 'neutral-dark'),
      anchor(250, 0.1, 0.35, 'main'),
      anchor(270, 0.08, 0.5, 'main'),
      anchor(45, 0.1, 0.75, 'accent', 8, 0.02, 0.05),
      anchor(240, 0.012, 0.9, 'neutral-light'),
    ],
    hueWindows: [
      { start: 220, end: 300 },
      { start: 20, end: 60 },
    ],
    chromaRange: [0.01, 0.14],
    lightnessRange: [0.08, 0.92],
    forbidden: [],
    defaultHarmony: 'analogous',
    warmth: 'cool',
    contrast: 'high',
    intensityBaseline: 'balanced',
    neutralProbability: 0.5,
  },
]
